---
# tasks file for ansible-role-prometheus
- name: "Prometheus group"
  group:
    name: "{{ prometheus_group }}"
    system: true
    state: "present"

- name: "Prometheus user"
  user:
    name: "{{ prometheus_user }}"
    system: true
    shell: "/sbin/falselogin"
    group: "{{ prometheus_group }}"
    createhome: false

- name: "Prometheus package"
  become: false
  get_url:
    url: "{{ prometheus_package_url }}"
    dest: "/tmp"
  register: "_prometheus_package"
  until: "_prometheus_package is succeeded"
  retries: 5
  delay: 2
  delegate_to: "localhost"
  run_once: true
  changed_when: false

- name: "Prometheus package unpacked"
  unarchive:
    src: "/tmp/{{ prometheus_package }}"
    dest: "/opt"
    creates: "/opt/{{ prometheus_package_base }}/prometheus"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: "Prometheus main link"
  file:
    state: "link"
    dest: "{{ prometheus_dir }}"
    src: "/opt/{{ prometheus_package_base }}"

- name: "Prometheus config dirs"
  file:
    state: "directory"
    path: "{{ prometheus_conf_dir }}"
    owner: "root"
    group: "{{ prometheus_group }}"
    mode: "0750"
  with_items:
    - "{{ prometheus_conf_dir }}"
    - "{{ prometheus_conf_rules_dir }}"

- name: "Prometheus config file"
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_conf_file }}"
    owner: "root"
    group: "{{ prometheus_group }}"
    mode: "0640"

- name: "Prometheus db path"
  file:
    state: "directory"
    path: "{{ prometheus_db_dir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: "Prometheus service file"
  template:
    src: "{{ prometheus_service }}.service.j2"
    dest: "/etc/systemd/system/{{ prometheus_service }}.service"

- name: "Prometheus service started"
  systemd:
    name: "{{ prometheus_service }}"
    state: "started"
    enabled: true
